steps:
  - name: "docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/hello-service",
        ".",
      ]
  - name: "docker"
    args: ["push", "gcr.io/$PROJECT_ID/hello-service"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:294.0.0-alpine"
    args:
      [
        "gcloud", "run", "deploy", "hello",
        "--image","gcr.io/$PROJECT_ID/hello-service",
        "--platform","managed",
        "--region", "us-central1",
        "--allow-unauthenticated",
      ]
    timeout: "300s"
images: 
  - "gcr.io/$PROJECT_ID/hello-service"
    
  